import { NextResponse } from 'next/server';


export const dynamic = 'force-dynamic';

/**
 * POST /api/ghl/test-push
 * Test endpoint to push Custom Values to GHL
 * Custom Values are used to display dynamic content in funnels
 * Merge tag format: {{custom_values.your_key}}
 */
export async function POST(req) {
  try {
    const body = await req.json();
    const { accessToken, locationId, customValueKey, customValueContent } = body;

    // Validate inputs
    if (!accessToken || !locationId) {
      return NextResponse.json({
        error: 'Missing required fields',
        required: ['accessToken', 'locationId'],
        optional: ['customValueKey', 'customValueContent']
      }, { status: 400 });
    }

    const key = customValueKey || 'test_headline';
    const value = customValueContent || 'Hello from TedOS! This headline was auto-generated by AI.';

    console.log('Testing GHL Custom Values push...');
    console.log('Location ID:', locationId);
    console.log('Custom Value Key:', key);
    console.log('Custom Value Content:', value);

    // GHL API endpoint for Custom Values
    const ghlApiUrl = `https://services.leadconnectorhq.com/locations/${locationId}/customValues`;

    console.log('Pushing to:', ghlApiUrl);

    // First, try to GET existing custom values to check if key exists
    const getResponse = await fetch(ghlApiUrl, {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Version': '2021-07-28'
      }
    });

    let existingValueId = null;
    if (getResponse.ok) {
      const existingData = await getResponse.json();
      const existingValue = existingData.customValues?.find(cv => cv.name === key);
      if (existingValue) {
        existingValueId = existingValue.id;
        console.log('Found existing custom value with ID:', existingValueId);
      }
    }

    let response;
    let method;

    if (existingValueId) {
      // UPDATE existing custom value
      method = 'PUT';
      response = await fetch(`${ghlApiUrl}/${existingValueId}`, {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
          'Version': '2021-07-28'
        },
        body: JSON.stringify({
          name: key,
          value: value
        })
      });
    } else {
      // CREATE new custom value
      method = 'POST';
      response = await fetch(ghlApiUrl, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
          'Version': '2021-07-28'
        },
        body: JSON.stringify({
          name: key,
          value: value
        })
      });
    }

    const responseText = await response.text();
    console.log('GHL Response Status:', response.status);
    console.log('GHL Response:', responseText);

    if (!response.ok) {
      let errorData;
      try {
        errorData = JSON.parse(responseText);
      } catch (e) {
        errorData = { message: responseText };
      }

      return NextResponse.json({
        success: false,
        error: 'GHL API error',
        method,
        status: response.status,
        details: errorData,
        troubleshooting: {
          401: 'Invalid Access Token - create a new Private Integration with customValues.write scope',
          403: 'Permission denied - ensure your integration has customValues.write permission',
          404: 'Location not found - verify your Location ID',
          422: 'Invalid data format',
          500: 'GHL server error - try again in a moment'
        }[response.status] || 'Unknown error'
      }, { status: response.status });
    }

    const data = JSON.parse(responseText);

    return NextResponse.json({
      success: true,
      message: existingValueId ? 'Custom value updated successfully!' : 'Custom value created successfully!',
      method,
      customValueKey: key,
      customValueContent: value,
      ghlResponse: data,
      howToUse: {
        mergeTag: `{{custom_values.${key}}}`,
        instructions: [
          '1. Go to GHL Dashboard → Your Funnel → Edit Page',
          '2. Click on any text element (headline, paragraph, etc.)',
          '3. In the text editor, type: {{custom_values.' + key + '}}',
          '4. Save and preview the page',
          '5. You should see: "' + value + '"'
        ]
      }
    });

  } catch (error) {
    console.error('Test push error:', error);
    return NextResponse.json({
      success: false,
      error: 'Internal server error',
      details: error.message,
      stack: process.env.NODE_ENV === 'development' ? error.stack : undefined
    }, { status: 500 });
  }
}


