-- ============================================
-- TED OS - 20 SECTIONS FIELD REFERENCE
-- ============================================
-- This is a DOCUMENTATION file only
-- NO DATABASE MIGRATION IS NEEDED because:
-- - saved_sessions.answers uses JSONB (stores any JSON structure)
-- - slide_results.ai_output uses JSONB (stores any JSON structure)
-- - intake_answers.answers uses JSONB (stores any JSON structure)
-- The new fields are automatically stored in these JSONB columns
-- ============================================
-- NEW FIELD NAMES (stored in JSONB columns)
-- 
-- Step 1:  industry          (text)      - What field do you work in?
-- Step 2:  idealClient       (text)      - Who do you help?
-- Step 3:  message           (text)      - What do you help them with?
-- Step 4:  coreProblem       (text)      - What problem are they facing?
-- Step 5:  outcomes          (text)      - What results do you help them achieve?
-- Step 6:  uniqueAdvantage   (text)      - What makes your approach different?
-- Step 7:  story             (text)      - Why do you do this work? Personal story
-- Step 8:  testimonials      (text)      - Client results or success stories
-- Step 9:  offerProgram      (text)      - Main program or service you offer
-- Step 10: deliverables      (text)      - What do people get when they join
-- Step 11: pricing           (text)      - What do you charge
-- Step 12: assets            (array)     - Marketing assets you have (multiselect)
-- Step 13: revenue           (string)    - Annual revenue range (dropdown)
-- Step 14: brandVoice        (text)      - Brand personality or voice
-- Step 15: brandColors       (text)      - Brand colors or visual style
-- Step 16: callToAction      (text)      - What you want people to do next
-- Step 17: platforms         (array)     - Where you want to get clients (multiselect)
--          platformsOther    (text)      - Custom platforms if "other" selected
-- Step 18: goal90Days        (text)      - #1 goal for next 90 days
-- Step 19: businessStage     (string)    - Beginner/Growth/Scaling (dropdown)
-- Step 20: helpNeeded        (text)      - What you need the most help with
-- DROPDOWN/MULTISELECT OPTIONS (defined in os-wizard-data.js)
--
-- ASSET_OPTIONS (Step 12):
--   free_gift, ads, landing_page, sales_page, emails, webinars, website, sales_script
--
-- REVENUE_OPTIONS (Step 13):
--   0-50k, 50k-100k, 100k-250k, 250k-500k, 500k-1m, 1m+
--
-- PLATFORM_OPTIONS (Step 17):
--   facebook, instagram, youtube, tiktok, email, website, referrals, not_sure, other
--
-- BUSINESS_STAGE_OPTIONS (Step 19):
--   beginner, growth, scaling
-- EXAMPLE: Data stored in saved_sessions.answers JSONB:
-- {
--   "industry": "marketing",
--   "idealClient": "coaches and consultants",
--   "message": "grow their business with AI",
--   "coreProblem": "struggling to get clients",
--   "outcomes": "10 new clients per month",
--   "uniqueAdvantage": "AI-powered marketing system",
--   "story": "I was a struggling coach...",
--   "testimonials": "Client A doubled revenue...",
--   "offerProgram": "12-Week Marketing Accelerator",
--   "deliverables": "weekly calls, templates, community",
--   "pricing": "$5,000",
--   "assets": ["landing_page", "emails", "website"],
--   "revenue": "50k-100k",
--   "brandVoice": "bold, inspirational",
--   "brandColors": "black and gold",
--   "callToAction": "book a call",
--   "platforms": ["facebook", "instagram", "email"],
--   "platformsOther": "",
--   "goal90Days": "get 10 clients",
--   "businessStage": "growth",
--   "helpNeeded": "marketing and sales"
-- }
-- NO SQL CHANGES REQUIRED - JSONB handles all field changes automatically