/**
 * @deprecated This module is no longer used.
 * 
 * Colors are now pushed directly as hex codes to GHL custom values
 * via the customValueMapper.js, eliminating the need for generated CSS.
 * 
 * Kept for reference in case custom CSS injection is needed in the future.
 * 
 * CSS Generation System
 * Generates custom CSS code for GHL funnels based on user's color preferences
 * Supports multiple AI providers: OpenAI, Claude, Gemini
 */

import { generateText, getProviderStatus } from '@/lib/ai/providerConfig';
import { supabase as supabaseAdmin } from '@/lib/supabaseServiceRole';

/**
 * Extract color scheme from user's answers
 */
export function extractColorScheme(sessionData) {
  const { answers } = sessionData;

  // Try different fields where colors might be stored
  const colors = answers.brandColors ||
    answers.preferredColors ||
    answers.colors ||
    answers.colorScheme ||
    {};

  // Default color scheme if not provided
  const defaultScheme = {
    primary: '#0891b2',      // Cyan
    secondary: '#06b6d4',    // Light cyan
    accent: '#22d3ee',       // Bright cyan
    text: '#ffffff',         // White
    textDark: '#1f2937',     // Dark gray
    background: '#0a0a0b',   // Almost black
    backgroundLight: '#1b1b1d' // Dark gray
  };

  return {
    primary: colors.primary || colors.main || defaultScheme.primary,
    secondary: colors.secondary || colors.accent || defaultScheme.secondary,
    accent: colors.accent || colors.highlight || defaultScheme.accent,
    text: colors.text || colors.textColor || defaultScheme.text,
    textDark: colors.textDark || colors.darkText || defaultScheme.textDark,
    background: colors.background || colors.bg || defaultScheme.background,
    backgroundLight: colors.backgroundLight || colors.bgLight || defaultScheme.backgroundLight
  };
}

/**
 * Generate CSS code using AI based on color scheme
 */
export async function generateCustomCSS(sessionData) {
  const colorScheme = extractColorScheme(sessionData);

  const prompt = `Generate comprehensive CSS code for a GoHighLevel funnel using this color scheme:
Primary: ${colorScheme.primary}
Secondary: ${colorScheme.secondary}
Accent: ${colorScheme.accent}
Text: ${colorScheme.text}
Text Dark: ${colorScheme.textDark}
Background: ${colorScheme.background}
Background Light: ${colorScheme.backgroundLight}

Requirements:
1. CSS classes for: buttons (primary, secondary, outline), headings (h1-h3), sections, text, backgrounds
2. Hover states for interactive elements
3. Gradient variations using the color scheme
4. Button styles with shadows and transitions
5. Section backgrounds (solid, gradient, subtle patterns)
6. Text color utilities for light and dark backgrounds
7. Border and accent colors
8. Card/box styling

Output ONLY the CSS code, no explanations. Use modern CSS with smooth transitions.

Format:
/* Primary Buttons */
.btn-primary { ... }

/* Secondary Buttons */
.btn-secondary { ... }

/* Headings */
h1, .heading-1 { ... }

/* Sections */
.section-primary { ... }

/* Text */
.text-primary { ... }

/* Backgrounds */
.bg-primary { ... }

Make it professional, modern, and ready to paste into GHL Custom CSS.

You are a professional CSS developer creating custom styles for marketing funnels. Output only CSS code, no markdown or explanations.`;

  try {
    // Log which provider is being used
    const providerStatus = getProviderStatus();
    console.log('Available AI providers:', providerStatus);

    let cssCode = await generateText(prompt, {
      temperature: 0.3,
      maxTokens: 2000
    });

    // Remove markdown code blocks if present (some providers might add them)
    cssCode = cssCode.replace(/```css\n?/g, '').replace(/```\n?/g, '').replace(/```/g, '');

    // Add header comment
    const header = `/* Custom CSS for GoHighLevel Funnel
 * Generated by TedOS AI
 * Color Scheme: ${colorScheme.primary} (Primary), ${colorScheme.secondary} (Secondary)
 * Copy and paste this into: GHL > Settings > Custom CSS
 */\n\n`;

    cssCode = header + cssCode;

    return {
      cssCode,
      colorScheme,
      sectionsIncluded: extractCssSections(cssCode)
    };

  } catch (error) {
    console.error('Error generating CSS:', error);

    // Fallback: Generate basic CSS without AI
    return {
      cssCode: generateFallbackCSS(colorScheme),
      colorScheme,
      sectionsIncluded: ['buttons', 'headings', 'text', 'backgrounds'],
      fallback: true
    };
  }
}

/**
 * Extract which sections are included in the CSS
 */
function extractCssSections(cssCode) {
  const sections = [];

  if (cssCode.includes('.btn-') || cssCode.includes('button')) sections.push('buttons');
  if (cssCode.includes('h1') || cssCode.includes('.heading')) sections.push('headings');
  if (cssCode.includes('.text-')) sections.push('text');
  if (cssCode.includes('.bg-')) sections.push('backgrounds');
  if (cssCode.includes('.section-')) sections.push('sections');
  if (cssCode.includes('.card-')) sections.push('cards');
  if (cssCode.includes('border')) sections.push('borders');
  if (cssCode.includes('gradient')) sections.push('gradients');

  return sections;
}

/**
 * Fallback CSS if AI generation fails
 */
function generateFallbackCSS(colorScheme) {
  return `/* Custom CSS for GoHighLevel Funnel
 * Generated by TedOS AI (Fallback)
 * Color Scheme: ${colorScheme.primary} (Primary), ${colorScheme.secondary} (Secondary)
 */

/* === BUTTONS === */
.btn-primary,
button.btn-primary,
.button-primary {
  background: ${colorScheme.primary} !important;
  color: ${colorScheme.text} !important;
  border: none !important;
  padding: 12px 32px !important;
  border-radius: 8px !important;
  font-weight: 600 !important;
  transition: all 0.3s ease !important;
  box-shadow: 0 4px 12px ${colorScheme.primary}33 !important;
}

.btn-primary:hover,
button.btn-primary:hover {
  background: ${colorScheme.secondary} !important;
  transform: translateY(-2px) !important;
  box-shadow: 0 6px 20px ${colorScheme.primary}44 !important;
}

.btn-secondary,
button.btn-secondary {
  background: transparent !important;
  color: ${colorScheme.primary} !important;
  border: 2px solid ${colorScheme.primary} !important;
  padding: 12px 32px !important;
  border-radius: 8px !important;
  font-weight: 600 !important;
  transition: all 0.3s ease !important;
}

.btn-secondary:hover {
  background: ${colorScheme.primary} !important;
  color: ${colorScheme.text} !important;
}

/* === HEADINGS === */
h1, .heading-1 {
  color: ${colorScheme.primary} !important;
  font-weight: 700 !important;
}

h2, .heading-2 {
  color: ${colorScheme.text} !important;
  font-weight: 600 !important;
}

h3, .heading-3 {
  color: ${colorScheme.textDark} !important;
  font-weight: 600 !important;
}

/* === TEXT === */
.text-primary {
  color: ${colorScheme.primary} !important;
}

.text-secondary {
  color: ${colorScheme.secondary} !important;
}

.text-accent {
  color: ${colorScheme.accent} !important;
}

.text-light {
  color: ${colorScheme.text} !important;
}

.text-dark {
  color: ${colorScheme.textDark} !important;
}

/* === BACKGROUNDS === */
.bg-primary {
  background: ${colorScheme.primary} !important;
  color: ${colorScheme.text} !important;
}

.bg-secondary {
  background: ${colorScheme.secondary} !important;
  color: ${colorScheme.text} !important;
}

.bg-dark {
  background: ${colorScheme.background} !important;
  color: ${colorScheme.text} !important;
}

.bg-light {
  background: ${colorScheme.backgroundLight} !important;
  color: ${colorScheme.text} !important;
}

.bg-gradient-primary {
  background: linear-gradient(135deg, ${colorScheme.primary}, ${colorScheme.secondary}) !important;
  color: ${colorScheme.text} !important;
}

/* === SECTIONS === */
.section-hero {
  background: ${colorScheme.background} !important;
  padding: 80px 20px !important;
}

.section-features {
  background: ${colorScheme.backgroundLight} !important;
  padding: 60px 20px !important;
}

.section-cta {
  background: linear-gradient(135deg, ${colorScheme.primary}, ${colorScheme.accent}) !important;
  padding: 60px 20px !important;
  color: ${colorScheme.text} !important;
}

/* === CARDS === */
.card {
  background: ${colorScheme.backgroundLight} !important;
  border: 1px solid ${colorScheme.primary}33 !important;
  border-radius: 12px !important;
  padding: 24px !important;
  transition: all 0.3s ease !important;
}

.card:hover {
  border-color: ${colorScheme.primary} !important;
  box-shadow: 0 8px 24px ${colorScheme.primary}22 !important;
  transform: translateY(-4px) !important;
}

/* === BORDERS & ACCENTS === */
.border-primary {
  border-color: ${colorScheme.primary} !important;
}

.border-accent {
  border-color: ${colorScheme.accent} !important;
}

.accent-line {
  height: 4px !important;
  width: 60px !important;
  background: ${colorScheme.accent} !important;
  margin: 16px 0 !important;
}

/* === FORMS === */
input[type="text"],
input[type="email"],
textarea {
  border: 2px solid ${colorScheme.backgroundLight} !important;
  border-radius: 8px !important;
  padding: 12px 16px !important;
  transition: border-color 0.3s ease !important;
}

input[type="text"]:focus,
input[type="email"]:focus,
textarea:focus {
  border-color: ${colorScheme.primary} !important;
  outline: none !important;
  box-shadow: 0 0 0 3px ${colorScheme.primary}22 !important;
}
`;
}

/**
 * Save generated CSS to database
 */
export async function saveGeneratedCSS(userId, sessionId, cssData) {
  const { data, error } = await supabaseAdmin
    .from('generated_css')
    .insert({
      user_id: userId,
      session_id: sessionId,
      css_code: cssData.cssCode,
      color_scheme: cssData.colorScheme,
      sections_covered: cssData.sectionsIncluded
    })
    .select()
    .single();

  if (error) {
    throw error;
  }

  return data;
}

/**
 * Get generated CSS for a session
 */
export async function getSessionCSS(sessionId) {
  const { data, error } = await supabaseAdmin
    .from('generated_css')
    .select('*')
    .eq('session_id', sessionId)
    .order('created_at', { ascending: false })
    .limit(1)
    .single();

  if (error && error.code !== 'PGRST116') { // Not found is OK
    console.error('Error fetching CSS:', error);
    return null;
  }

  return data;
}
