"use client";
import { useState } from "react";
import { Rocket, CheckCircle, XCircle, Loader2, AlertCircle } from "lucide-react";
import { toast } from "sonner";

export default function TestGHLPage() {
  const [accessToken, setAccessToken] = useState('');
  const [locationId, setLocationId] = useState('');
  const [customFieldName, setCustomFieldName] = useState('test_headline');
  const [customFieldValue, setCustomFieldValue] = useState('Hello from TedOS! This headline was auto-generated by AI.');
  const [testing, setTesting] = useState(false);
  const [result, setResult] = useState(null);

  const handleTest = async () => {
    if (!accessToken || !locationId) {
      toast.error('Please enter both Access Token and Location ID');
      return;
    }

    setTesting(true);
    setResult(null);

    try {
      const res = await fetch('/api/ghl/test-push', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          accessToken,
          locationId,
          customFieldName,
          customFieldValue
        })
      });

      const data = await res.json();
      setResult(data);

      if (data.success) {
        toast.success('Successfully pushed to GHL!');
      } else {
        toast.error('Push failed: ' + data.error);
      }

    } catch (error) {
      console.error('Test error:', error);
      toast.error('Failed to connect: ' + error.message);
      setResult({
        success: false,
        error: 'Network error',
        details: error.message
      });
    } finally {
      setTesting(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#0a0a0b] text-white p-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold mb-2 bg-gradient-to-r from-cyan to-blue-500 bg-clip-text text-transparent">
            GHL Integration Test
          </h1>
          <p className="text-gray-400">
            Test pushing a single custom value to GoHighLevel before full integration
          </p>
        </div>

        {/* Setup Instructions */}
        <div className="bg-[#1b1b1d] border border-cyan/30 rounded-lg p-6 mb-8">
          <div className="flex items-start gap-3 mb-4">
            <AlertCircle className="w-5 h-5 text-cyan flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="text-lg font-semibold text-cyan mb-2">Before Testing</h3>
              <ol className="text-sm text-gray-300 space-y-2 list-decimal list-inside">
                <li>Create a custom field in GHL: Settings → Custom Fields → Add "test_headline" (Text type)</li>
                <li>Create a simple funnel page in GHL</li>
                <li>Add this to any text element: <code className="bg-black/50 px-2 py-1 rounded">{'{{custom_values.test_headline}}'}</code></li>
                <li>Get your API credentials from GHL Settings → Integrations → API Key</li>
                <li>Enter credentials below and click Test Push</li>
              </ol>
            </div>
          </div>
        </div>

        {/* Test Form */}
        <div className="bg-[#1b1b1d] border border-[#2a2a2d] rounded-lg p-8 mb-8">
          <h2 className="text-2xl font-bold mb-6">GHL Credentials</h2>

          <div className="space-y-6">
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Access Token (API Key) <span className="text-red-500">*</span>
              </label>
              <input
                type="password"
                value={accessToken}
                onChange={(e) => setAccessToken(e.target.value)}
                placeholder="Paste your GHL API access token here"
                className="w-full px-4 py-3 bg-[#0a0a0b] border border-[#2a2a2d] rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-cyan transition-colors"
              />
              <p className="text-xs text-gray-500 mt-1">
                Found in GHL: Settings → Integrations → API Key
              </p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Location ID <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                value={locationId}
                onChange={(e) => setLocationId(e.target.value)}
                placeholder="abc123-def456-ghi789..."
                className="w-full px-4 py-3 bg-[#0a0a0b] border border-[#2a2a2d] rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-cyan transition-colors"
              />
              <p className="text-xs text-gray-500 mt-1">
                Found in your GHL URL: /location/<strong>[THIS_PART]</strong>/dashboard
              </p>
            </div>

            <div className="border-t border-[#2a2a2d] pt-6">
              <h3 className="text-lg font-semibold mb-4">Test Data</h3>

              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Custom Field Name
                  </label>
                  <input
                    type="text"
                    value={customFieldName}
                    onChange={(e) => setCustomFieldName(e.target.value)}
                    placeholder="test_headline"
                    className="w-full px-4 py-3 bg-[#0a0a0b] border border-[#2a2a2d] rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-cyan transition-colors"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    Must match the field name you created in GHL
                  </p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Test Value
                  </label>
                  <textarea
                    value={customFieldValue}
                    onChange={(e) => setCustomFieldValue(e.target.value)}
                    placeholder="Enter test content..."
                    rows={3}
                    className="w-full px-4 py-3 bg-[#0a0a0b] border border-[#2a2a2d] rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-cyan transition-colors resize-none"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    This will be pushed to GHL and displayed in your funnel
                  </p>
                </div>
              </div>
            </div>

            <button
              onClick={handleTest}
              disabled={testing || !accessToken || !locationId}
              className="w-full px-6 py-4 bg-gradient-to-r from-cyan to-blue-500 hover:from-cyan/90 hover:to-blue-500/90 disabled:from-gray-700 disabled:to-gray-700 disabled:cursor-not-allowed rounded-lg font-bold text-lg flex items-center justify-center gap-3 transition-all shadow-lg shadow-cyan/20"
            >
              {testing ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Testing Connection...
                </>
              ) : (
                <>
                  <Rocket className="w-5 h-5" />
                  Test Push to GHL
                </>
              )}
            </button>
          </div>
        </div>

        {/* Results */}
        {result && (
          <div className={`border rounded-lg p-6 ${result.success ? 'bg-green-500/10 border-green-500/30' : 'bg-red-500/10 border-red-500/30'}`}>
            <div className="flex items-start gap-3">
              {result.success ? (
                <CheckCircle className="w-6 h-6 text-green-500 flex-shrink-0" />
              ) : (
                <XCircle className="w-6 h-6 text-red-500 flex-shrink-0" />
              )}

              <div className="flex-1">
                <h3 className={`text-lg font-bold mb-2 ${result.success ? 'text-green-500' : 'text-red-500'}`}>
                  {result.success ? 'Success!' : 'Failed'}
                </h3>

                {result.success ? (
                  <div className="space-y-4">
                    <p className="text-gray-300">{result.message}</p>

                    <div className="bg-black/30 rounded-lg p-4">
                      <p className="text-sm text-gray-400 mb-2">Field Details:</p>
                      <div className="space-y-1 text-sm">
                        <p><span className="text-gray-500">Name:</span> <code className="text-cyan">{result.fieldName}</code></p>
                        <p><span className="text-gray-500">Value:</span> <span className="text-white">{result.fieldValue}</span></p>
                      </div>
                    </div>

                    {result.nextSteps && (
                      <div>
                        <p className="text-sm font-semibold text-gray-300 mb-2">Next Steps:</p>
                        <ol className="text-sm text-gray-400 space-y-1">
                          {result.nextSteps.map((step, i) => (
                            <li key={i}>{step}</li>
                          ))}
                        </ol>
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="space-y-3">
                    <p className="text-red-400">{result.error}</p>

                    {result.details && (
                      <div className="bg-black/30 rounded-lg p-4">
                        <p className="text-sm text-gray-400 mb-2">Error Details:</p>
                        <pre className="text-xs text-red-400 overflow-x-auto">
                          {JSON.stringify(result.details, null, 2)}
                        </pre>
                      </div>
                    )}

                    {result.troubleshooting && (
                      <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-4">
                        <p className="text-sm font-semibold text-yellow-500 mb-1">Troubleshooting:</p>
                        <p className="text-sm text-yellow-200">{result.troubleshooting}</p>
                      </div>
                    )}

                    {result.status === 422 && (
                      <div className="bg-blue-500/10 border border-blue-500/30 rounded-lg p-4">
                        <p className="text-sm text-blue-300">
                          <strong>Note:</strong> If the field already exists, this is expected.
                          Try changing the custom field name or delete the existing field in GHL first.
                        </p>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Debug Info */}
        {result?.ghlResponse && (
          <details className="mt-4 bg-[#1b1b1d] border border-[#2a2a2d] rounded-lg p-4">
            <summary className="cursor-pointer text-sm text-gray-400 font-mono">
              Show GHL API Response (Debug)
            </summary>
            <pre className="text-xs text-gray-500 mt-4 overflow-x-auto">
              {JSON.stringify(result.ghlResponse, null, 2)}
            </pre>
          </details>
        )}
      </div>
    </div>
  );
}
